---
- name: Shutdown Windows Servers
  hosts: win01
  gather_facts: no
  tasks:
    - name: Initiate graceful shutdown
      win_shell: shutdown /s /t 0
      async: 900  # Adjust the timeout value as needed
      poll: 0
