---
- name: Install and configure Zabbix Agent
  hosts: redhat:!zap01
  become: yes  # Use sudo to become root

  tasks:
    - name: Install Zabbix 6 repository
      yum:
              #name: https://repo.zabbix.com/zabbix/5.5/rhel/8/x86_64/zabbix-release-5.5-1.el8.noarch.rpm
        name: https://repo.zabbix.com/zabbix/7.0/rhel/8/x86_64/zabbix-release-7.0-2.el8.noarch.rpm
        state: present
        validate_certs: no
      tags: zabbix_install

    - name: Install Zabbix Agent
      yum:
        name: zabbix-agent2
        state: present
      tags: zabbix_install

    - name: Backup Zabbix Agent configuration
      command: cp /etc/zabbix/zabbix_agent2.conf /etc/zabbix/zabbix_agent2.conf-backup
      tags: zabbix_configure

    - name: Update Zabbix Agent configuration
      lineinfile:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      with_items:
        - { regexp: '^Server=127.0.0.1', line: 'Server=172.16.1.212' }
        - { regexp: '^ServerActive=127.0.0.1', line: 'ServerActive=172.16.1.212' }
        - { regexp: '^Hostname=Zabbix server', line: 'Hostname={{ ansible_hostname }}' }
        - { regexp: '^# HostMetadata=', line: 'HostMetadata=LinuxServer' }
      notify: restart zabbix-agent
      tags: zabbix_configure

    - name: Ensure Zabbix Agent is started and enabled
      systemd:
        name: zabbix-agent2
        state: started
        enabled: yes
      tags: zabbix_configure

  handlers:
    - name: restart zabbix-agent
      systemd:
        name: zabbix-agent2
        state: restarted
