---
- name: Create a VM from a template
  hosts: localhost
  gather_facts: false
  collections:
  - community.vmware
  connection: local
  pre_tasks:
  - include_vars: vars.yml

  tasks:
  - name: Clone the template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: False
      name: "{{ vm_name }}"
      state: present
      template: "{{ template_name }}"
    # datastore: "{{ virtual_machine_datastore }}"
      folder : "/darole-dc/vm"
      datacenter: "darole-dc"
      hardware:
        memory_mb: 1024
        num_cpus: 1
        scsi: paravirtual
