---
- name: Assign execute permission and schedule table update script.
  hosts: lamp01
  become: yes
  tasks:
    - name: Assign execute permission to script
      file: 
        path: /var/www/html/table-data-update.sh
        mode: "+x"

    - name: Schedule the table update script for every hour uning cron.
      cron:
        name: Run table update script
        minute: "*/50"
        hour: "*"
        job: /var/www/html/table-data-update.sh
